authorized_for_system_information=nagiosadmin,username1
authorized_for_configuration_information=nagiosadmin,username1
authorized_for_system_commands=nagiosadmin,username1
authorized_for_all_services=nagiosadmin,username1
authorized_for_all_hosts=nagiosadmin,username1
authorized_for_all_service_commands=nagiosadmin,username1
authorized_for_all_host_commands=nagiosadmin,username1